# Author        ：Rabbit
# Create        ：20210505
# Update       ：20250209  默认关闭http/socks5/redir,补全部分备注
# Description ：clash通用配置，仪表盘通过 http://<external-controller>/ui 访问

#混合代理端口（http+socks）
mixed-port: 7890

# HTTP 代理端口（默认使用混合代理）
# port: 7891 

# SOCKS5 代理端口（默认使用混合代理）
# socks-port: 7892 

# Linux 和 macOS 的 redir 代理端口（默认使用混合代理）
# redir-port: 7893 

# 允许局域网的连接
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: rule

# 设置日志输出级别（默认级别:info，日志内容可能过大而导致程序内存溢出）
# 5 个级别:silent / info / warning / error / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# Clash 的 RESTful API：0.0.0.0为所有地址
external-controller: '0.0.0.0:50456'

# RESTful API 的口令
secret: 'b&ZlKTte5OnEt2Sn'

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# external-ui: /code/clash-dashboard

